package:
  name: nbsite
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.{{ GIT_BUILD_STR }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python >=3.6
    - notebook
    - ipython
    - sphinx
    - beautifulsoup4
    - graphviz
    - selenium
    - phantomjs

#test:
#  imports:
#    - parambokeh

about:
  home: https://github.com/ioam/nbsite
  summary: abc123
  license: BSD 3-Clause
